### ISSUE TITLE
MI tests failing

### ISSUE THREAD

**Issue by dayanne-castro** [simonsfoundation/inferelator_ng#41]
Mutual information tests all failing for me... how is it looking for you guys? Anything I should be aware of that is changing?

**Comment by NicoDeVeaux** [comment]
@dayanne-castro The master branch code hasn't changed since April. I'm not seeing failures. What branch are you on?

**Comment by dayanne-castro** [comment]
Nick, it is in the MTL branch actually -- I didn't change anything with mi though..

**Comment by NicoDeVeaux** [comment]
Locally, the tests pass for me on branch master. However, if I run the tests on branch MTL in a different directory (`/Users/ndeveaux/Dropbox (Simons Foundation)/inferelator_refactor`), then all the mi tests fail. The reason they fail, however, has nothing to do with mi code correctness: it's because the test infrastructure can't handle running R code from a directory with a space in it, i.e. "Dropbox (Simons Foundation)"
I moved the code to a `~/Desktop/tmp` folder, and the MI tests passed. However, I still got one test failure: ```======================================================================
ERROR: test_ebic_RSSzero (inferelator_ng.tests.test_sparse_blocksparse.Test_AuxiliaryFunctions)
----------------------------------------------------------------------```
`Traceback (most recent call last):
  File "/Users/ndeveaux/Desktop/tmp/inferelator_ng/inferelator_ng/tests/test_sparse_blocksparse.py", line 31, in test_ebic_RSSzero
    self.assertAlmostEqual(sparse_blocksparse.ebic(self.X, self.Y, W, 2, 2, [3, 3]), 2.07944)
  File "/Users/ndeveaux/Desktop/tmp/inferelator_ng/inferelator_ng/sparse_blocksparse.py", line 294, in ebic
    n = n_samples[k]
TypeError: 'int' object has no attribute '__getitem__'`

**Comment by dayanne-castro** [comment]
Got it!

About the error -- still working on it, and I haven't even committed how did you get it? 
D.
